### ISSUE TITLE
driver.load_api method not working

### ISSUE THREAD

**Issue by Prussian1870** [FirebirdSQL/python3-driver#1]
Hi:

I'm using Version 0.8.0 and I can't seem to get the driver.load_api method to work. I tried using forward and backward slashes and I still get an error. In this example I'm using the r(raw) indicator:

import firebird as fdb

fdb.driver.load_api(r"c:\working\fbdll\fbclient.dll")

The error returned is: "argument of type 'WindowsPath' is not iterable"

Thanks

**Comment by pcisar** [comment]
Well, I cannot reproduce with version 1.0.0. If your problem persist even with 1.0.1, please show me the stack trace for this exception.

**Comment by Prussian1870** [comment]
line1934c:\working\fbdll\fbclient.dll
Traceback (most recent call last):
    fdriver.load_api(r"c:\working\fbdll\fbclient.dll")
  File "C:\Python\Python38\lib\site-packages\firebird\driver\fbapi.py", line 2045, in load_api
    _api = FirebirdAPI(filename)
  File "C:\Python\Python38\lib\site-packages\firebird\driver\fbapi.py", line 1935, in __init__
    self.client_library: ctypes.CDLL = ctypes.WinDLL(filename)
  File "C:\Python\Python38\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by Prussian1870** [comment]
line1934c:\working\fbdll\fbclient.dll
Traceback (most recent call last):
    fdriver.load_api(r"c:\working\fbdll\fbclient.dll")
  File "C:\Python\Python38\lib\site-packages\firebird\driver\fbapi.py", line 2045, in load_api
    _api = FirebirdAPI(filename)
  File "C:\Python\Python38\lib\site-packages\firebird\driver\fbapi.py", line 1935, in __init__
    self.client_library: ctypes.CDLL = ctypes.WinDLL(filename)
  File "C:\Python\Python38\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by pcisar** [comment]
Try latest 3.8 Python release (3.8.6)
